// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using HospitalManagementSystem.Data.Data;

#nullable disable

namespace HospitalManagementSystem.DBContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328160000_AddMissingAuditColumnsToAllTables")]
    partial class AddMissingAuditColumnsToAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            // This is a placeholder for the designer file
#pragma warning restore 612, 618
        }
    }
}
