// <auto-generated />
using System;
using HospitalManagementSystem.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagementSystem.DBContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327130000_AddRoleToUserMaster")]
    partial class AddRoleToUserMaster
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            // This migration only adds the Role column to UserMaster
            // Full model snapshot is inherited from previous migrations
#pragma warning restore 612, 618
        }
    }
}
